### ISSUE TITLE
config.REDIS is ignored.

### ISSUE THREAD

**Issue by sheenobu** [sockethub/sockethub#191]
No matter how you configure sockethub, 127.0.0.1 is always used as redis server. PR incoming, by replacing each redisPool with a shared redisPool attached to the sockethub class. May not be ideal; I would love some input.

EDIT: for knowledge, I'm using sockethub as part of working through https://unhosted.org/adventures/6/Controlling-your-server-over-a-WebSocket.html.

**Comment by silverbucket** [comment]
hi @sheenobu - thanks for reporting the issue. It should be mentioned that we've got a functional rewrite of sockethub on the branch `experimental_v1_0`. This issue may be fixed there, also the code is more simplified overall.

**Comment by silverbucket** [comment]
Although I haven't yet update the documentation, there's the basic getting started stuff in the README on that branch.

**Comment by sheenobu** [comment]
Thanks. Looks like it. Wrote the patch but good thing I procrastinated on testing it =)

**Comment by Cobertos** [comment]
Is there a patch for this? I'm encountering the same issue on `v4.0.1` (it was working on master but I downgraded cause I was getting some other weird stuff).

Output of `--info`
```
root@6c69331a1f8a:/app# packages/sockethub/bin/sockethub --info
sockethub 4.0.0

examples enabled: false
sockethub: localhost:10550/sockethub
redis: redis:6379
public url: localhost:10550/

platforms: dummy, feeds, irc, xmpp

  dummy v2.1.0
    AS @types: credentials, echo, fail

  feeds v2.2.0
    AS @types: 

  irc v3.6.0
    AS @types: credentials, update, join, leave, send, observe, announce

  xmpp v4.0.0
    AS @types: credentials, connect, update, send, join, observe, request-friend, remove-friend, make-friend
```

yet still seeing this error in `docker-compose logs -f`

```
2021-08-23T09:14:49.870Z sockethub:platform:irc:37cb5d7 platform handler initialized for irc 37cb5d7
sockethub_1  | 2021-08-23T09:14:49.876Z sockethub:platform:irc:37cb5d7 listening on the queue for incoming jobs
sockethub_1  | (node:31) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:6379
sockethub_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
sockethub_1  | (Use `node --trace-warnings ...` to show where the warning was created)
sockethub_1  | (node:31) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
sockethub_1  | (node:31) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
sockethub_1  | (node:31) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:6379
sockethub_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
sockethub_1  | (node:31) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
sockethub_1  | 2021-08-23T09:15:07.322Z sockethub:janitor sessions: 2 instances: 1
sockethub_1  | 2021-08-23T09:16:07.341Z sockethub:janitor sessions: 2 instances: 1
```

**Comment by Cobertos** [comment]
Oof, that was a pain in the ass to track down. Making a PR

**Comment by Cobertos** [comment]
Not the same issue as the 2015 one, but same symptoms

**Comment by silverbucket** [comment]
Closing as this is not the same issue that @Cobertos reported
