### ISSUE TITLE
sockethub won't start on master with node v4.2.6

### ISSUE THREAD

**Issue by abliss** [sockethub/sockethub#206]
```
abliss@localhost:~/proj/sockethub$ bin/sockethub


UNCAUGHT EXCEPTION - something horrible has happened!

Error: SyntaxError: Unexpected token [
    at module.exports (/home/abliss/proj/sockethub/lib/bootstrap/platforms.js:52:17)
    at Object.<anonymous> (/home/abliss/proj/sockethub/lib/bootstrap/init.js:10:53)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/abliss/proj/sockethub/lib/sockethub.js:16:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

**Comment by abliss** [comment]
Caused by:
```
abliss@localhost:~/proj/sockethub$ node -e 'require("sockethub-platform-irc")'
/home/abliss/proj/sockethub/node_modules/sockethub-platform-irc/index.js:473
          var [ username, channel, message ] = object.params;
              ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
```

**Comment by abliss** [comment]
I guess I'm running an older version of node (4.2.6) that doesn't support the "Destructuring Assignment Syntax". I'll try upgrading, but I suppose this should be mandated by package.json?

**Comment by abliss** [comment]
Workaround:
```
$ node --harmony-destructuring bin/sockethub
```

**Comment by skddc** [comment]
> I'll try upgrading, but I suppose this should be mandated by package.json?

Yes, I think the `engines` entry should require whatever the minimum version is for the features used. Not sure which one that would be, but as 6.x is LTS, that would probably the most reasonable choice at the moment.

**Comment by silverbucket** [comment]
Ah, yeah I started leaking es6 syntax into the code without realizing it and didn't think to update the package with base node requirements. 6.x+ will definitely work. Not sure about making it a requirement though, as people can still use 4.x with the right flags (as @abliss mentioned). But perhaps it should be documented somewhere.

**Comment by skddc** [comment]
I think it's easier to just use a supported node version than going online, finding the documentation for some outdated flag, and applying that to the start command.
