### ISSUE TITLE
Invalid credential objects crash Sockethub instance

### ISSUE THREAD

**Issue by skddc** [sockethub/sockethub#212]
Also see https://github.com/sockethub/sockethub-platform-xmpp/issues/4

**Comment by silverbucket** [comment]
```
  sockethub:worker:k09Kj79iIohBzkCfAAAJ:irc calling: join +0ms
  sockethub:worker:k09Kj79iIohBzkCfAAAJ:irc:module join() called for irc://hyper_nick@irc.freenode.net +0ms
  sockethub:worker:k09Kj79iIohBzkCfAAAJ:irc:module using existing client instance. irc://hyper_nick@irc.freenode.net +0ms
  sockethub:worker:k09Kj79iIohBzkCfAAAJ:irc:module got client for irc://hyper_nick@irc.freenode.net +0ms
  sockethub:worker:k09Kj79iIohBzkCfAAAJ:irc:module join: hyper_nick -> #sockethub +0ms
  sockethub:validate validating activity-object +1ms
  sockethub:validate validating message +2ms

UNCAUGHT EXCEPTION - something horrible has happened!

Error: invalid property: "displayname"
    at Object.Stream (/Users/njenning/code/projects/sockethub/node_modules/activity-streams/lib/activity-streams.js:101:13)
    at /Users/njenning/code/projects/sockethub/lib/validate.js:60:31
    at _callFunc (/Users/njenning/code/projects/sockethub/lib/middleware.js:29:18)
    at Socket.<anonymous> (/Users/njenning/code/projects/sockethub/lib/middleware.js:39:5)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at /Users/njenning/code/projects/sockethub/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
njenning@prg-mp6q0 sockethub$ 
```

**Comment by silverbucket** [comment]
```
  sockethub:worker:FcxN3vuLQ8UQKeEaAAAE:xmpp:module received buddy presence update: hermes@5apps.com - online +0ms
  sockethub:worker:g3-yie9NZEo5HIqiAAAF:xmpp:module received buddy presence update: hermes@5apps.com - online +0ms
  sockethub:worker:8x-ca4IFUlCACSfBAAAI:xmpp:module received buddy presence update: hermes@5apps.com - online +0ms

UNCAUGHT EXCEPTION - something horrible has happened!

TypeError: Cannot read property 'isConnected' of undefined
    at Object.isConnected (/Users/njenning/code/projects/sockethub-platform-irc/index.js:511:70)
    at /Users/njenning/code/projects/node-connection-manager/lib/manager.js:44:85
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
njenning@prg-mp6q0 sockethub$ 

```

**Comment by galfert** [comment]
This seems to break (at least) the IRC functionality. When trying to join a channel I now get a failure message with the error

> "AssertionError: session.client.get first param must be a unique identifier string (job.actor.id?)"

**Comment by silverbucket** [comment]
Ah OK, having a look now, if you can, please always put the full stack track when possible:

caught error:  AssertionError: session.client.get first param must be a unique identifier string (job.actor.id?)
    at Object.get (/Users/njenning/code/projects/sockethub/lib/session.js:143:7)
    at XMPP.join (/Users/njenning/code/projects/sockethub-platform-xmpp/index.js:210:34)
    at Domain.<anonymous> (/Users/njenning/code/projects/sockethub/lib/worker.js:111:49)
    at Domain.run (domain.js:221:14)
    at /Users/njenning/code/projects/sockethub/lib/worker.js:105:15
    at Worker.<anonymous> (/Users/njenning/code/projects/sockethub/node_modules/kue/lib/queue/worker.js:227:7)
    at Job.<anonymous> (/Users/njenning/code/projects/sockethub/node_modules/kue/lib/queue/job.js:699:12)
    at multi_callback (/Users/njenning/code/projects/sockethub/node_modules/redis/lib/multi.js:89:14)
    at Command.<anonymous> (/Users/njenning/code/projects/sockethub/node_modules/redis/lib/multi.js:116:9)
    at bound (domain.js:280:14)
    at Command.runBound [as callback] (domain.js:293:12)
    at normal_reply (/Users/njenning/code/projects/sockethub/node_modules/redis/index.js:721:21)
    at RedisClient.return_reply (/Users/njenning/code/projects/sockethub/node_modules/redis/index.js:819:9)
    at JavascriptRedisParser.returnReply (/Users/njenning/code/projects/sockethub/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/Users/njenning/code/projects/sockethub/node_modules/redis-parser/lib/parser.js:560:12)
    at Socket.<anonymous> (/Users/njenning/code/projects/sockethub/node_modules/redis/index.js:274:27) +0ms

**Comment by skddc** [comment]
I think it would be good, if we all did PRs here, so people can review changes and new bugs are less likely to enter `master`.

**Comment by silverbucket** [comment]
@galfert this is fixed and pushed to master now, but still writing some tests after which i'll bump the version

**Comment by silverbucket** [comment]
@skddc sure, glad to have people willing to review PRs :)

**Comment by galfert** [comment]
I can confirm that it works now.

**Comment by silverbucket** [comment]
One issue with using pull requests is that I've got several different repos for different modules. A lot of work depends on changes in other repos. How can I manage this efficiently while waiting for a PR in one branch, and having other fixes in other repos assosciated with them? Seems like it could get hairy pretty quickly, Any suggestions welcome.

**Comment by silverbucket** [comment]
And `v1.2.1` should be pretty stable now, i spent a lot of time greatly improving the testing process of incoming JSON data, but that involved some restructuring of the code, so there could be some areas that got missed, please report them with steps to reproduce and I will address them asap.

**Comment by skddc** [comment]
Great, thanks!
