### ISSUE TITLE
Graceful recovery from platform errors

### ISSUE THREAD

**Issue by silverbucket** [sockethub/sockethub#217]
During some race conditions, the IRC connection will report as being connected, but the actual instance won't be defined, so calls to `raw` will throw an error. This seems to leave Sockethub in a state of limbo where incoming messages don't get routed and processed.

```
  sockethub:core:u1jiGue0WO18xHCQAAAB processing activity-object +1ms
  sockethub:core:u1jiGue0WO18xHCQAAAB processing credentials +0ms
  sockethub:core:u1jiGue0WO18xHCQAAAB processing activity-object +1ms
  sockethub:core:u1jiGue0WO18xHCQAAAB processing incoming message +0ms
  sockethub:core:u1jiGue0WO18xHCQAAAB processing activity-object +0ms
  sockethub:core:u1jiGue0WO18xHCQAAAB processing incoming message +0ms
  sockethub:core:u1jiGue0WO18xHCQAAAB processing activity-object +0ms
  sockethub:core:u1jiGue0WO18xHCQAAAB processing incoming message +0ms
  sockethub:core:u1jiGue0WO18xHCQAAAB processing activity-object +0ms
  sockethub:core:u1jiGue0WO18xHCQAAAB processing credentials +0ms
  sockethub:core:u1jiGue0WO18xHCQAAAB processing incoming message +0ms
  sockethub:core:u1jiGue0WO18xHCQAAAB processing activity-object +1ms
  sockethub:core:u1jiGue0WO18xHCQAAAB processing incoming message +0ms
  sockethub:core:u1jiGue0WO18xHCQAAAB credentials encrypted and saved to irc://hyper_nick@irc.freenode.net +0ms
  sockethub:core:u1jiGue0WO18xHCQAAAB credentials encrypted and saved to xmpp://hermes@5apps.com@xmpp.5apps.com +2ms
  sockethub:worker:u1jiGue0WO18xHCQAAAB got job: join xvrAMtsq9bAezGfR +4ms
  sockethub:worker:u1jiGue0WO18xHCQAAAB creating new platform instance of irc for u1jiGue0WO18xHCQAAAB +0ms
  sockethub:worker:u1jiGue0WO18xHCQAAAB:irc calling: join +0ms
  sockethub:worker:u1jiGue0WO18xHCQAAAB:irc:module join() called for irc://hyper_nick@irc.freenode.net +0ms
  sockethub:worker:u1jiGue0WO18xHCQAAAB:irc:module got config for irc://hyper_nick@irc.freenode.net +1ms
  sockethub:worker:u1jiGue0WO18xHCQAAAB:irc:module creating connection manager record. +0ms
  sockethub:worker:u1jiGue0WO18xHCQAAAB:irc:module attempting to connect to irc.freenode.net:7000 [secure:true] +0ms
  sockethub-platform-irc *: {"target":"*","message":"*** No Ident response","time":"2017-05-13T22:05:25.257Z","raw":":wilhelm.freenode.net NOTICE * :*** No Ident response"} +7s
  sockethub-platform-irc *: {"raw":[":wilhelm.freenode.net 251 hyper_nick :There are 134 users and 88270 invisible on 27 servers",":wilhelm.freenode.net 252 hyper_nick 28 :IRC Operators online",":wilhelm.freenode.net 253 hyper_nick 13 :unknown connection(s)",":wilhelm.freenode.net 254 hyper_nick 59884 :channels formed",":wilhelm.freenode.net 255 hyper_nick :I have 5143 clients and 1 servers",":wilhelm.freenode.net 265 hyper_nick 5143 10018 :Current local users 5143, max 10018",":wilhelm.freenode.net 266 hyper_nick 88404 96186 :Current global users 88404, max 96186"],"channels":"59884","local":"5143","localmax":"10018","global":"88404","globalmax":"96186","time":"2017-05-13T22:05:25.263Z"} +6ms
  sockethub:worker:u1jiGue0WO18xHCQAAAB:irc:module connected to irc.freenode.net +6s
  sockethub:worker:u1jiGue0WO18xHCQAAAB:irc:module addListener called! irc://hyper_nick@irc.freenode.net * +1ms
  sockethub:worker:u1jiGue0WO18xHCQAAAB:irc:module join: -> #hackerbeach +1ms
  sockethub:worker:NnVU36-ZBkKlZhqzAAAA:irc caught error:  TypeError: Cannot read property 'raw' of undefined
    at /Users/njenning/code/projects/sockethub-platform-irc/index.js:186:26
    at /Users/njenning/code/projects/sockethub/lib/session.js:177:13
    at /Users/njenning/code/projects/node-connection-manager/lib/manager.js:298:5
    at EventEmitter.onRegister (/Users/njenning/code/projects/sockethub-platform-irc/index.js:875:9)
    at EventEmitter.emit (/Users/njenning/code/projects/sockethub-platform-irc/node_modules/irc-factory/node_modules/eventemitter2/lib/eventemitter2.js:332:22)
    at Client._sendRegistered (/Users/njenning/code/projects/sockethub-platform-irc/node_modules/irc-factory/lib/irc.js:1491:9)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5) +2ms
  sockethub:worker:NnVU36-ZBkKlZhqzAAAA:irc disposing of domain +1ms
  sockethub:worker:u1jiGue0WO18xHCQAAAB:irc:module sending motd +3ms
  sockethub-platform-irc verifying username hyper_nick against hyper_nick +20ms
  sockethub:core failed job: 1 TypeError: Cannot read property 'raw' of undefined +2ms
  sockethub:core job [1] failed for socket NnVU36-ZBkKlZhqzAAAA +1ms
  sockethub:core removed failed job #1 +0ms
  sockethub:worker:NnVU36-ZBkKlZhqzAAAA got job: join dLNhKsMJuRgGuSCq +1ms
  sockethub:worker:NnVU36-ZBkKlZhqzAAAA creating new platform instance of xmpp for NnVU36-ZBkKlZhqzAAAA +0ms
  sockethub:worker:NnVU36-ZBkKlZhqzAAAA:xmpp calling: join +0ms
  sockethub:core failed job: 2 unable to decrypt +3ms
  sockethub:core job [2] failed for socket NnVU36-ZBkKlZhqzAAAA +0ms
  sockethub:core removed failed job #2 +1ms
  sockethub:worker:NnVU36-ZBkKlZhqzAAAA got job: cleanup dLNhKsMJuRgGuSCq +1ms
  sockethub:worker:NnVU36-ZBkKlZhqzAAAA:xmpp calling: cleanup +0ms
  sockethub:worker:NnVU36-ZBkKlZhqzAAAA:xmpp:module cleanup called, but nothing implemented +1ms
  sockethub:core received completed job for non-existent socket +3ms
  sockethub:worker:NnVU36-ZBkKlZhqzAAAA got job: cleanup dLNhKsMJuRgGuSCq +1ms
  sockethub:core received completed job for non-existent socket +1ms
  sockethub:worker:NnVU36-ZBkKlZhqzAAAA got job: cleanup dLNhKsMJuRgGuSCq +2ms
  sockethub:core received completed job for non-existent socket +2ms
  sockethub:worker:NnVU36-ZBkKlZhqzAAAA got job: cleanup dLNhKsMJuRgGuSCq +1ms
  sockethub:core received completed job for non-existent socket +1ms
  sockethub:worker:NnVU36-ZBkKlZhqzAAAA:xmpp end of cleanup, calling platform.session.connection.removeAll() +5s
  sockethub:worker:NnVU36-ZBkKlZhqzAAAA:irc:module connection manager create failed:  unable to connect, timeout [30000] reached. +17s
  sockethub:worker:u1jiGue0WO18xHCQAAAB:irc:module attempting to connect to irc.freenode.net:7000 [secure:true] +30s
  sockethub:validate validating message +26s
  sockethub:core:u1jiGue0WO18xHCQAAAB processing incoming message +4ms
```

**Comment by skddc** [comment]
![thumbs_up_waynes_world](https://user-images.githubusercontent.com/842/46945145-55426b00-d074-11e8-8496-d6cf2ba4f631.gif)
