### ISSUE TITLE
Error: Cannot find module 'tv4'

### ISSUE THREAD

**Issue by raucao** [sockethub/sockethub#633]
After updating my repo to current `master`, and installing npm modules, I get the following exception when starting Sockethub:

```
$ DEBUG=sockethub* ./bin/sockethub
  sockethub:bootstrap:config initializing config +0ms
UNCAUGHT EXCEPTION
Error: Cannot find module 'tv4'
Require stack:
- /home/basti/src/sockethub/sockethub/packages/sockethub/dist/bootstrap/platforms.js
- /home/basti/src/sockethub/sockethub/packages/sockethub/dist/bootstrap/init.js
- /home/basti/src/sockethub/sockethub/packages/sockethub/dist/sockethub.js
- /home/basti/src/sockethub/sockethub/packages/sockethub/bin/sockethub
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/basti/src/sockethub/sockethub/packages/sockethub/dist/bootstrap/platforms.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
error Command failed with exit code 1.
```

**Comment by raucao** [comment]
Just to confirm: `sockethub@4.0.1` still works for me.

**Comment by galfert** [comment]
There is a commit that switches from `tv4` to `ajv` at 85af3158.

It seems that after that the distribution files haven't been updated yet.

Running `yarn run install` and `yarn run build` fixed it for me.

**Comment by raucao** [comment]
Ah, thanks!
