### ISSUE TITLE
Sockethub shutting down instead of handling exception

### ISSUE THREAD

**Issue by raucao** [sockethub/sockethub#726]
This is happening in Hyperchannel tests, where Sockethub shuts down entirely with the following stack trace when it seems like it may receive a malformed message of some sort:

```
UNCAUGHT EXCEPTION

TypeError: Cannot read properties of null (reading 'type')
    at getTypeList (/home/travis/sockethub/packages/schemas/dist/helpers/error-parser.js:23:59)
    at getTypes (/home/travis/sockethub/packages/schemas/dist/helpers/error-parser.js:52:17)
    at getErrorMessage (/home/travis/sockethub/packages/schemas/dist/helpers/error-parser.js:64:19)
    at handleValidation (/home/travis/sockethub/packages/schemas/dist/validator.js:35:43)
    at Object.validateActivityStream (/home/travis/sockethub/packages/schemas/dist/validator.js:44:12)
    at Array.<anonymous> (/home/travis/sockethub/packages/server/dist/middleware/validate.js:39:43)
    at next (/home/travis/sockethub/packages/server/dist/middleware.js:43:43)
    at Array.expandActivityStream (/home/travis/sockethub/packages/server/dist/middleware/expand-activity-stream.js:28:13)
    at next (/home/travis/sockethub/packages/server/dist/middleware.js:43:43)
    at Socket.<anonymous> (/home/travis/sockethub/packages/server/dist/middleware.js:49:13)
```

See https://github.com/67P/hyperchannel/pull/288/commits/1bc9ec0b615d75c99e82b34f8273c4cfec607098 and https://app.travis-ci.com/github/67P/hyperchannel/builds/249687679 for an example build with the Sockethub stack trace. You can run that branch against a local Sockethub and observe it crashing, even when the tests do succeed every now and then (i.e. the next test is faster than the Sockethub shutdown).

**Comment by silverbucket** [comment]
OK, I want to say this was something related to a `null` object (where in a part of the older code I was checking if `typeof` is `object` which returns true for `null`). So hopefully writing some tests with more unexpected/undefined properties, and fixing the code should remove this problem.

**Comment by silverbucket** [comment]
Oops! I accidentally committed and pushed this fix straight to master. All tests are passing here, can you verify this no longer shows up for you? https://github.com/sockethub/sockethub/commit/668f9cc81acb228d279d79a10ace3df674175513

**Comment by raucao** [comment]
You should set up branch protection for master, so that this cannot happen accidentally.

**Comment by raucao** [comment]
I just updated the [Hyperchannel PR](https://github.com/67P/hyperchannel/pull/288) and unfortunately it's still crashing Sockethub (output from my local run):

```
  sockethub:validate:gmsoPfhmINJPIcqgAAAB applying schema validation for message +0ms
UNCAUGHT EXCEPTION                                                                    
TypeError: Cannot read property 'type' of null
    at getTypeList (/home/basti/src/sockethub/sockethub/packages/schemas/dist/helpers/error-parser.js:23:59)
    at getTypes (/home/basti/src/sockethub/sockethub/packages/schemas/dist/helpers/error-parser.js:52:17)
    at getErrorMessage (/home/basti/src/sockethub/sockethub/packages/schemas/dist/helpers/error-parser.js:64:19)       
    at handleValidation (/home/basti/src/sockethub/sockethub/packages/schemas/dist/validator.js:35:43)
    at Object.validateActivityStream (/home/basti/src/sockethub/sockethub/packages/schemas/dist/validator.js:44:12)
    at Array.<anonymous> (/home/basti/src/sockethub/sockethub/packages/server/dist/middleware/validate.js:39:43)
    at next (/home/basti/src/sockethub/sockethub/packages/server/dist/middleware.js:43:43)                        
    at Array.expandActivityStream (/home/basti/src/sockethub/sockethub/packages/server/dist/middleware/expand-activity-stream.js:28:13)
    at next (/home/basti/src/sockethub/sockethub/packages/server/dist/middleware.js:43:43)              
    at Socket.<anonymous> (/home/basti/src/sockethub/sockethub/packages/server/dist/middleware.js:49:13)
destroying all platform instances
```

**Comment by silverbucket** [comment]
@raucao Hmm, it's odd that the error is on the same line. Perhaps you need to run `yarn build`? My dist output has line 23 as a closing curly brace `}`.

**Comment by raucao** [comment]
Sorry, the actual line is 18 with the latest build:

```
  sockethub:validate:5xRmAoQWGqG0cNkUAAAB applying schema validation for message +0ms
UNCAUGHT EXCEPTION
TypeError: Cannot read property 'type' of null
    at getTypeList (/home/basti/src/sockethub/sockethub/packages/schemas/dist/helpers/error-parser.js:18:59)
    at getTypes (/home/basti/src/sockethub/sockethub/packages/schemas/dist/helpers/error-parser.js:47:17)
    at getErrorMessage (/home/basti/src/sockethub/sockethub/packages/schemas/dist/helpers/error-parser.js:59:19)
    at handleValidation (/home/basti/src/sockethub/sockethub/packages/schemas/dist/validator.js:35:43)
    at Object.validateActivityStream (/home/basti/src/sockethub/sockethub/packages/schemas/dist/validator.js:44:12)
    at Array.<anonymous> (/home/basti/src/sockethub/sockethub/packages/server/dist/middleware/validate.js:39:43)
    at next (/home/basti/src/sockethub/sockethub/packages/server/dist/middleware.js:43:43)
    at Array.expandActivityStream (/home/basti/src/sockethub/sockethub/packages/server/dist/middleware/expand-activity-stream.js:28:13)
    at next (/home/basti/src/sockethub/sockethub/packages/server/dist/middleware.js:43:43)
    at Socket.<anonymous> (/home/basti/src/sockethub/sockethub/packages/server/dist/middleware.js:49:13)
destroying all platform instances
```
